Bjorn248/scca_classifier

common.js

- Added Eagle data to complete #27

Add Eagle Data

---

common.js

Ferrari added

---

common.js

Daewoo cars added. close issue #51

Daewoo cars added

---

common.js

consolidate MP4-12C years

---

common.js

feat: Added Triumph vehicles

---

common.js

Kia updates

---

common.js

i added shelby cars to the common.js file

Add all Shelby vehicles to common.js #38

---

common.js

Add all Morgan vehicles to common.js

---

common.js

done https://github.com/Bjorn248/scca_classifier/issues/23

Add all Jensen vehicles to common.js

---

common.js

issue #10 initial Mazda addition

---

common.js

issue #22 initial Fiat addition

---

a/st.html
common.js

Just adds some questions to get street touring started

issue #127 add some street touring questions

---

common.js

Adds Pontiac addresses issue #12

---

common.js

Fingers crossed I did it correctly this time lol.

adding Saturn take two!

---

a/st.html
common.js

issue: #127 finish street touring questions

---

src/a/s.html
src/a/st.html
src/common.js

* separates highlight function into two functions, one for each class
* found a fixed a bug related to having a shared answered index between
classes, fixed by creating separate index for each class

issue #158

---

src/common.js

Resolves #57 
Also removes some duplicate models found under other makes...there should be a ticket to resolve this for Dodge/Chrysler/Plymouth going forward, it can get confusing.

add Plymouth

---

src/a/s.html
src/a/ssc.html
src/a/st.html
src/common.js

* Adds SSC Questions
* Gets rid of `’`, `“`, and `”` in favor of `'` and `"`

add SSC questions

---

src/a/xs.html
src/common.js

issue 133 adds Xtreme Street questions

---

src/a/s.html
src/a/st.html
src/common.js

issue 173 add Street Touring Overview page

---

src/a/sm.html
src/a/st.html
src/common.js

issue 129 adds SM questions

---

src/a/cam.html
src/a/s.html
src/a/sm.html
src/a/sp.html
src/a/ssc.html
src/a/st.html
src/a/xs.html
src/common.js

issue 128 add street prepared questions

---

src/a/p.html
src/common.js

Issue 130 add questions for prepared

---

src/a/m.html
src/common.js

Resolves #131 for now, just to add a placeholder

adds placeholder for modified questions

---

src/index.html

add github link to homepage

---

terraform/.gitignore
terraform/.terraform.lock.hcl
terraform/infra.tf

Adds terraform to describe the project infrastructure, Relates #126

Issue 126 add terraform

---

README.md

adds build status to README

---

src/common.js

issue 198 - add non-torsen diff miata model

---

src/common.js

issue 193 - add suzuki cappuccino

---

src/common.js

issue 199 fix STI classing

---

src/common.js

remove camc from all cobalts

---

src/common.js

Resolves #201 
Used python jsbeautifier...long term solution would be to add sorting to the JS that populates the select elements, I figured this was good enough for now

issue 201 offline sort the makes/models in common.js

---

src/common.js

issue 208 fix brz classing

---

src/a/cam.html
src/a/m.html
src/a/p.html
src/a/s.html
src/a/sm.html
src/a/sp.html
src/a/ssc.html
src/a/st.html
src/a/xs.html

issue 200 add scroll to top action when each question is answered

---

src/a/cam.html
src/a/m.html
src/a/p.html
src/a/s.html
src/a/sm.html
src/a/sp.html
src/a/ssc.html
src/a/st.html
src/a/xs.html
src/styles.css

issue 223 add some divs, clean up some classes, add margins to questions

---

src/common.js

issue 225 add toyota 86 to stx

---

src/a/cam.html
src/a/m.html
src/a/p.html
src/a/s.html
src/a/sm.html
src/a/sp.html
src/a/ssc.html
src/a/st.html
src/a/xs.html
src/styles.css

Issue 228 rename reset button

---

src/a/st.html
src/styles.css

issue 229 set css max-width property for mobile screens

---

src/a/index.html

issue 232 inform users of rough class ordering

---

src/a/index.html
src/common.js

Adds a NOC (Not Otherwise Classified) make with a few of the "Catch-All" categories as models

add NOC make and catch-all models

---

src/common.js

Fixed V6 Fiero stock classing from CS to ES.

Fixed V6 Fiero classing

---

src/common.js

Should fix issue https://github.com/Bjorn248/scca_classifier/issues/246

issue-246 fix crossfire classing

---

CONTRIBUTING.md

Explains how to edit where cars go.

Make contributing a little easier.

---

CONTRIBUTING.md

Provides some basic instructions for contributing. Inspired by https://github.com/Bjorn248/scca_classifier/pull/245

Issue 248 improve instructions

---

src/a/index.html
src/index.html
src/rr/index.html

issue-253 add lang attribute

---

src/index.html

issue-255 update latest rules URL on homepage

---

src/common.js

issue: #257 add missing years to E63 AMG

---

.github/workflows/build.js.yml
.github/workflows/lint.js.yml
package-lock.json
package.json

issue 266: upgrade to node 18

---

src/common.js

bit of a drive-by/toe-dipping test

Added C6 years to Corvette Grand Sport model

---

src/styles.css

I don't understand CSS well enough to know why this fixes it...yet

change width to allow right box to have margin from right border

---

src/a/cam.html
src/a/x.html

issue 283: fix driver weight wording for cam/xtreme

---

.github/workflows/build.js.yml
.github/workflows/lint.js.yml

update to nodejs 22

---

.github/workflows/build.js.yml
.github/workflows/lint.js.yml

saw some warnings in the actions tab about deprecated node versions being used so I'm updating

update github actions to latest versions

---

src/common.js
templates/common.js.tmpl

issue 309: address as/ss misclassing

---

src/common.js
templates/common.js.tmpl

issue 311: add 5-series to g street

---

src/common.js
templates/common.js.tmpl

add gr corolla to stu

---

src/common.js
templates/common.js.tmpl

issue 315: update impreza 2.5

---

src/common.js
templates/common.js.tmpl

issue 321: fix mazda3 turbo classing

---

CONTRIBUTING.md
README.md
package-lock.json

I noticed the docs were a bit stale, also a bonus `npm audit fix`

slightly improve readme/contributing docs

---

src/common.js
templates/common.js.tmpl

issue 329 add WRX TR and tS

---

src/common.js
templates/common.js.tmpl

issue-333 fix EVX classing

---

src/common.js
templates/common.js.tmpl

Resolves #334 
Adds GST to WRX TR and tS

issue-334 fix WRX classing

---

src/common.js
templates/common.js.tmpl

issue-337 add civic hybrid

---

src/common.js
templates/common.js.tmpl

issue-339 fix civic sport classing

---

src/common.js
templates/common.js.tmpl

Remove 2016 Honda Civic Si

---

src/common.js
templates/common.js.tmpl

fix civic mugen classing

---

src/common.js
templates/common.js.tmpl

issue-350 fix mazda3 turbo classing

---

src/a/x.html

issue-353 XS fixes

---

generate_rules_txt.sh
src/a/st.html
src/common.js
templates/common.js.tmpl

issue-352 March 2025 fastrack updates

---

src/common.js
templates/common.js.tmpl

issue-357 fix 240Z classing

---

src/common.js
templates/common.js.tmpl

issue-361 add Lexus GS 430

---

src/common.js
templates/common.js.tmpl

issue-364 july 2025 fastrack

---

src/a/cam.html
src/a/csm.html
src/a/csx.html
src/a/ev.html
src/a/index.html
src/a/m.html
src/a/p.html
src/a/s.html
src/a/sm.html
src/a/sp.html
src/a/ssc.html
src/a/st.html
src/a/x.html
src/common.js
src/index.html
src/styles.css

The style of the website is a bit dated. Trying to use AI to help facilitate some modernization changes. These changes were made almost entirely by prompting claude sonnet 4 with cascade

Modernization

---

package-lock.json
src/styles.css

modernization fixes

---

src/styles.css

Drop down text is white on select, unreadable with the new dark theme
Make drop down text always black

drop down select bug fix

---

src/common.js
src/styles.css

This will hopefully improve the issues raised in #372

issue-372 subclass text light, capitalize subclass
